// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTDQrgBQG_RL7wsQ6YVFATJ8dExcJflxc',
    appId: '1:433438242336:android:599e88faf7fe5d579f6e45',
    messagingSenderId: '433438242336',
    projectId: 'crud-app-26eed',
    storageBucket: 'crud-app-26eed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_4zvKmIJJK82kfzG36QLo4ah3wKAyTOw',
    appId: '1:433438242336:ios:b595aa9341df06e99f6e45',
    messagingSenderId: '433438242336',
    projectId: 'crud-app-26eed',
    storageBucket: 'crud-app-26eed.appspot.com',
    androidClientId: '433438242336-8egbc9ehimakru959gjd173h9s4ugkqd.apps.googleusercontent.com',
    iosClientId: '433438242336-jg80sfit7mmp0jiutorehmed2faucjjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudApp',
  );
}
